# High-Value Customer Behavior Simulation for a FinTech Subscription Service

Version: v02: 2026-04-08 / v01: 2026-04-04

> The Business Problem: Company CCC has a small set of "VIP Customer" data. Because of GDPR/Privacy laws, the Data Science team cannot use this data in the general development environment. They need a high-fidelity synthetic twin of these VIP customers to stress-test a new AI-driven Credit Limit model without risking real PII (Personally Identifiable Information).

## SECTION S03: Data Analysis

> Objective: Illustrate how to use Bayesian Inference to prove that the synthetic data is a "faithful twin" of the real data.

> The Fidelity Challenge: If we didn't have the original seed data, could we guess the "True" business parameters just by looking at the synthetic data?

> Statistical Distance: Use src.analysis.calculate_kl_divergence to measure how far the GAN-generated distribution is from the Seed distribution.

> Bayesian Parameter Recovery:

> Business Conclusion: "The synthetic data recovers the real-world mean μ≈750 with a 95% credible interval of ±2, proving the GAN is safe for model testing."

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import torch
from torch import nn
from torch.utils.data import DataLoader, TensorDataset

from scipy.stats import norm
import pymc as pm

ModuleNotFoundError: No module named 'pymc3'

In [3]:
if '..' not in sys.path:
    sys.path.append('..')

from src.analysis import recover_parameters, calculate_kl_divergence

ModuleNotFoundError: No module named 'pymc'

In [2]:
df_synth = pd.read_csv('../data/checkpoints/vip_seed.csv')
df_synth

     avg_transaction  frequency  credit_score  vip_status
0          15.215716        7.0    678.557138           0
1                NaN       10.0    761.094175           0
2          30.511738       14.0    910.000000           1
3                NaN        9.0    272.000000           0
4                NaN        5.0    890.000000           0
..               ...        ...           ...         ...
125        30.733056       19.0    727.632877           1
126              NaN       12.0    775.330201           0
127       839.056973       11.0    738.298211           0
128              NaN       10.0    297.000000           0
129        18.432976      -15.0    718.583193           0

[130 rows x 4 columns]

In [4]:
# Use PyMC to estimate the mean and sigma of the synthetic population
trace = recover_parameters(df_synth)
trace

ModuleNotFoundError: No module named 'pymc'

In [5]:
# Plot the posterior distribution of the mean
import arviz as az
az.plot_posterior(trace)
# Business Conclusion: "The synthetic data recovers the real-world mean μ≈750 with a 95% credible interval of ±2, proving the GAN is safe for model testing.

ImportError: cannot import name 'gaussian' from 'scipy.signal' (/Users/rserban/.pyenv/versions/3.9.10/lib/python3.9/site-packages/scipy/signal/__init__.py)

### Synthetic Data Fidelity Assessment
#### 1. Generate synthetic data using GANs.
#### 2. Evaluate its statistical fidelity using KL-divergence.
#### 3. Perform Bayesian parameter recovery to test whether synthetic data captures the "true" business parameters.
#### 4. Make business conclusions about synthetic data utility.

In [ ]:
sns.set(style="whitegrid")
torch.manual_seed(42)
np.random.seed(42)

# %% [markdown]
# ## 1. Load Seed Data

# Example: synthetic business metric data (e.g., transaction amounts)
seed_data = pd.read_csv("data/seed_data.csv")
x_seed = seed_data['transaction_amount'].values.astype(np.float32)

plt.hist(x_seed, bins=30, alpha=0.6, color='blue')
plt.title("Seed Data Distribution")
plt.xlabel("Transaction Amount")
plt.ylabel("Frequency")
plt.show()

# %% [markdown]
# ## 2. Build a Simple GAN to Generate Synthetic Data

# Generator
class Generator(nn.Module):
    def __init__(self, noise_dim=1, output_dim=1):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(noise_dim, 16),
            nn.ReLU(),
            nn.Linear(16, 32),
            nn.ReLU(),
            nn.Linear(32, output_dim)
        )
    def forward(self, z):
        return self.model(z)

# Discriminator
class Discriminator(nn.Module):
    def __init__(self, input_dim=1):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, 32),
            nn.ReLU(),
            nn.Linear(32, 16),
            nn.ReLU(),
            nn.Linear(16, 1),
            nn.Sigmoid()
        )
    def forward(self, x):
        return self.model(x)

# %% [markdown]
# ### Training the GAN

noise_dim = 1
G = Generator(noise_dim)
D = Discriminator()

criterion = nn.BCELoss()
lr = 0.001
optimizer_G = torch.optim.Adam(G.parameters(), lr=lr)
optimizer_D = torch.optim.Adam(D.parameters(), lr=lr)

epochs = 2000
batch_size = 64

data_loader = DataLoader(TensorDataset(torch.tensor(x_seed).unsqueeze(1)), batch_size=batch_size, shuffle=True)

for epoch in range(epochs):
    for real_batch, in data_loader:
        batch_size_curr = real_batch.size(0)
        # Train Discriminator
        z = torch.randn(batch_size_curr, noise_dim)
        fake_batch = G(z)
        
        D_loss = criterion(D(real_batch), torch.ones(batch_size_curr, 1)) + \
                 criterion(D(fake_batch.detach()), torch.zeros(batch_size_curr, 1))
        
        optimizer_D.zero_grad()
        D_loss.backward()
        optimizer_D.step()
        
        # Train Generator
        G_loss = criterion(D(fake_batch), torch.ones(batch_size_curr, 1))
        optimizer_G.zero_grad()
        G_loss.backward()
        optimizer_G.step()

# %% [markdown]
# ## 3. Generate Synthetic Data

z = torch.randn(1000, noise_dim)
x_synth = G(z).detach().numpy().flatten()

plt.hist(x_synth, bins=30, alpha=0.6, color='orange')
plt.title("Synthetic Data Distribution")
plt.xlabel("Transaction Amount")
plt.ylabel("Frequency")
plt.show()

# %% [markdown]
# ## 4. Statistical Distance: KL-Divergence

kl_div = calculate_kl_divergence(x_seed, x_synth)
print(f"KL Divergence (Seed vs Synthetic): {kl_div:.4f}")

# %% [markdown]
# ## 5. Bayesian Parameter Recovery

# Assume we believe the real data is normally distributed
with pm.Model() as model:
    mu = pm.Normal("mu", mu=0, sigma=1000)
    sigma = pm.HalfNormal("sigma", sigma=500)
    observed = pm.Normal("observed", mu=mu, sigma=sigma, observed=x_synth)
    
    trace = pm.sample(2000, tune=1000, cores=2, random_seed=42)

pm.plot_posterior(trace, var_names=["mu"])
plt.show()

mu_mean = trace["mu"].mean()
mu_hdi = pm.hdi(trace["mu"], hdi_prob=0.95)
print(f"Recovered μ = {mu_mean:.2f}, 95% CI = ±{(mu_hdi[1]-mu_hdi[0])/2:.2f}")

# %% [markdown]
# ## 6. Business Conclusion

print(
    f"The synthetic data recovers the real-world mean μ≈{mu_mean:.0f} "
    f"with a 95% credible interval of ±{(mu_hdi[1]-mu_hdi[0])/2:.2f}, "
    "proving the GAN is safe for model testing."
)

In [13]:
df = pd.read_csv('../data/raw/vip_seed.csv')
df

    avg_transaction  frequency  credit_score
0         15.215716          7    678.557138
1         12.344233         10    761.094175
2         30.511738         14    672.995701
3         18.419750          9    762.615895
4         17.161261          5    734.068630
..              ...        ...           ...
95        25.319317         11    730.921455
96        16.781139         11    738.298211
97        70.238607         11    716.194463
98        29.667821         13    692.157533
99        20.947708         14    796.192209

[100 rows x 3 columns]

In [18]:
frequency = df['frequency'].fillna(0.0)
avg_transaction = df['avg_transaction'].fillna(0.0)
credit_score = df['credit_score'].fillna(0.0)
rfm_score = (avg_transaction / 100) * (credit_score / 700) * (frequency / 10)
vip_status = (rfm_score > np.percentile(rfm_score, 70)).astype(int)
df['vip_status'] = vip_status.fillna(0.0).astype(int)
df

    avg_transaction  frequency  credit_score  vip_status
0         15.215716          7    678.557138           0
1         12.344233         10    761.094175           0
2         30.511738         14    672.995701           1
3         18.419750          9    762.615895           0
4         17.161261          5    734.068630           0
..              ...        ...           ...         ...
95        25.319317         11    730.921455           0
96        16.781139         11    738.298211           0
97        70.238607         11    716.194463           1
98        29.667821         13    692.157533           1
99        20.947708         14    796.192209           0

[100 rows x 4 columns]

In [19]:
df_corrupt = introduce_nans(df, proportion=0.2)
df_corrupt

    avg_transaction  frequency  credit_score  vip_status
0         15.215716        7.0    678.557138         0.0
1         12.344233       10.0    761.094175         NaN
2         30.511738        NaN    672.995701         1.0
3         18.419750        NaN    762.615895         NaN
4         17.161261        5.0    734.068630         0.0
..              ...        ...           ...         ...
95        25.319317       11.0    730.921455         0.0
96        16.781139       11.0    738.298211         0.0
97              NaN       11.0    716.194463         1.0
98        29.667821       13.0    692.157533         1.0
99        20.947708       14.0    796.192209         0.0

[100 rows x 4 columns]

### Check data quality issues

In [21]:
# 1. Missing values (MCAR, MAR, MNAR patterns)
# MCAR: Random 5% missing in avg_transaction
mcar_idx = np.random.choice(df.index, size=int(0.05 * n_samples), replace=False)
df.loc[mcar_idx, 'avg_transaction'] = np.nan

# MAR: Missing credit_score when avg_transaction is low (10% of low-value customers)
low_value_mask = df['avg_transaction'] < np.percentile(df['avg_transaction'].dropna(), 30)
mar_idx = df[low_value_mask].sample(frac=0.10, random_state=42).index
df.loc[mar_idx, 'credit_score'] = np.nan

# MNAR: Missing frequency for VIP customers (they don't need to track frequency)
vip_mask = df['vip_status'] == 1
mnar_idx = df[vip_mask].sample(frac=0.15, random_state=42).index
df.loc[mnar_idx, 'frequency'] = np.nan
df

    avg_transaction  frequency  credit_score  vip_status
0         15.215716        7.0    678.557138           0
1               NaN       10.0    761.094175           0
2         30.511738       14.0    672.995701           1
3               NaN        9.0    762.615895           0
4               NaN        5.0    734.068630           0
..              ...        ...           ...         ...
95              NaN       11.0    730.921455           0
96        16.781139       11.0    738.298211           0
97              NaN       11.0    716.194463           1
98              NaN       13.0    692.157533           1
99              NaN       14.0    796.192209           0

[100 rows x 4 columns]

#### Detect outliers

In [22]:
# Extreme outliers in avg_transaction (data entry errors)
outlier_idx = np.random.choice(df.index, size=20, replace=False)
df.loc[outlier_idx, 'avg_transaction'] = df.loc[outlier_idx, 'avg_transaction'] * 50  # 50x inflation

# Impossible credit scores (< 300 or > 850)
corrupt_idx = np.random.choice(df.index, size=15, replace=False)
df.loc[corrupt_idx[:8], 'credit_score'] = np.random.randint(100, 299, 8)
df.loc[corrupt_idx[8:], 'credit_score'] = np.random.randint(851, 999, 7)

# Negative frequencies (data corruption)
neg_idx = np.random.choice(df.index, size=10, replace=False)
df.loc[neg_idx, 'frequency'] = -df.loc[neg_idx, 'frequency']
df

    avg_transaction  frequency  credit_score  vip_status
0         15.215716        7.0    678.557138           0
1               NaN       10.0    761.094175           0
2         30.511738       14.0    910.000000           1
3               NaN        9.0    272.000000           0
4               NaN        5.0    890.000000           0
..              ...        ...           ...         ...
95              NaN       11.0    730.921455           0
96       839.056973       11.0    738.298211           0
97              NaN       11.0    716.194463           1
98              NaN       13.0    692.157533           1
99              NaN       14.0    796.192209           0

[100 rows x 4 columns]

In [23]:
# 3. Duplicate records
duplicates = df.sample(n=30, random_state=42)
df = pd.concat([df, duplicates], ignore_index=True)
df

     avg_transaction  frequency  credit_score  vip_status
0          15.215716        7.0    678.557138           0
1                NaN       10.0    761.094175           0
2          30.511738       14.0    910.000000           1
3                NaN        9.0    272.000000           0
4                NaN        5.0    890.000000           0
..               ...        ...           ...         ...
125        30.733056       19.0    727.632877           1
126              NaN       12.0    775.330201           0
127       839.056973       11.0    738.298211           0
128              NaN       10.0    297.000000           0
129        18.432976      -15.0    718.583193           0

[130 rows x 4 columns]

In [25]:
# Save the corrupted dataset to output directory
df.to_csv('../data/checkpoints/vip_seed.csv', index=False)

#### Data quality check

In [24]:
print("=" * 70)
print("SYNTHETIC DATASET CREATED: vip_seed.csv")
print("=" * 70)
print(f"Total samples: {len(df)}")
print(f"Features: avg_transaction, credit_score, frequency")
print(f"Target: vip_status (binary)")
print(f"\nClass distribution:")
print(df['vip_status'].value_counts())
print(f"\nMissing values:")
print(df.isnull().sum())
print(f"\nData corruption examples:")
print(f"- Credit scores outside [300, 850]: {((df['credit_score'] < 300) | (df['credit_score'] > 850)).sum()}")
print(f"- Negative frequencies: {(df['frequency'] < 0).sum()}")
print(f"- Extreme transaction outliers: {(df['avg_transaction'] > 10000).sum()}")
print(f"- Duplicate rows: {df.duplicated().sum()}")

======================================================================
SYNTHETIC DATASET CREATED: vip_seed.csv
======================================================================
Total samples: 130
Features: avg_transaction, credit_score, frequency
Target: vip_status (binary)

Class distribution:
vip_status
0    94
1    36
Name: count, dtype: int64

Missing values:
avg_transaction    93
frequency           5
credit_score        4
vip_status          0
dtype: int64

Data corruption examples:
- Credit scores outside [300, 850]: 25
- Negative frequencies: 14
- Extreme transaction outliers: 0
- Duplicate rows: 30